<?php

namespace Fereydooni\Shopping\app\Facades;

use Fereydooni\Shopping\app\Services\CustomerWishlistService;
use Illuminate\Support\Facades\Facade;

/**
 * @method static \Illuminate\Database\Eloquent\Collection getAllWishlists()
 * @method static \Illuminate\Pagination\LengthAwarePaginator getPaginatedWishlists(int $perPage = 15)
 * @method static \Illuminate\Pagination\Paginator getSimplePaginatedWishlists(int $perPage = 15)
 * @method static \Illuminate\Pagination\CursorPaginator getCursorPaginatedWishlists(int $perPage = 15, string $cursor = null)
 * @method static \Fereydooni\Shopping\app\Models\CustomerWishlist|null getWishlist(int $id)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO|null getWishlistDTO(int $id)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO createWishlist(array $data)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO|null updateWishlist(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist, array $data)
 * @method static bool deleteWishlist(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO addProductToWishlist(int $customerId, int $productId, array $data = [])
 * @method static bool removeProductFromWishlist(int $customerId, int $productId)
 * @method static bool isInWishlist(int $customerId, int $productId)
 * @method static \Illuminate\Database\Eloquent\Collection getCustomerWishlist(int $customerId)
 * @method static \Illuminate\Database\Eloquent\Collection getCustomerWishlistByPriority(int $customerId)
 * @method static \Illuminate\Database\Eloquent\Collection getCustomerWishlistByDateAdded(int $customerId, string $order = 'desc')
 * @method static \Illuminate\Database\Eloquent\Collection getCustomerWishlistByPrice(int $customerId, string $order = 'desc')
 * @method static \Illuminate\Database\Eloquent\Collection searchCustomerWishlist(int $customerId, string $query)
 * @method static bool makeWishlistPublic(int $wishlistId)
 * @method static bool makeWishlistPrivate(int $wishlistId)
 * @method static bool setWishlistPriority(int $wishlistId, string $priority)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO|null updateWishlistNotes(int $wishlistId, string $notes)
 * @method static bool updateWishlistCurrentPrice(int $wishlistId, float $currentPrice)
 * @method static \Illuminate\Database\Eloquent\Collection checkWishlistPriceDrops(int $customerId)
 * @method static bool markWishlistAsNotified(int $wishlistId)
 * @method static bool markWishlistAsNotNotified(int $wishlistId)
 * @method static bool clearCustomerWishlist(int $customerId)
 * @method static array exportCustomerWishlist(int $customerId)
 * @method static bool importCustomerWishlist(int $customerId, array $wishlistItems)
 * @method static bool duplicateCustomerWishlist(int $sourceCustomerId, int $targetCustomerId)
 * @method static \Illuminate\Database\Eloquent\Collection getWishlistRecommendations(int $customerId, int $limit = 10)
 * @method static \Illuminate\Database\Eloquent\Collection getSimilarWishlists(int $customerId, int $limit = 10)
 * @method static array getWishlistAnalytics(int $customerId)
 * @method static array getWishlistStats()
 * @method static array getWishlistStatsByCustomer(int $customerId)
 * @method static array getPriceDropStats()
 * @method static array getPriceDropStatsByCustomer(int $customerId)
 * @method static \Illuminate\Database\Eloquent\Collection getMostWishlistedProducts(int $limit = 10)
 * @method static \Illuminate\Database\Eloquent\Collection getMostWishlistedProductsByCategory(int $categoryId, int $limit = 10)
 * @method static \Illuminate\Database\Eloquent\Collection getRecentWishlistAdditions(int $limit = 10)
 * @method static \Illuminate\Database\Eloquent\Collection getRecentWishlistAdditionsByCustomer(int $customerId, int $limit = 10)
 * @method static bool validateWishlistData(array $data)
 * @method static int getWishlistCountByCustomer(int $customerId)
 * @method static float getTotalWishlistValueByCustomer(int $customerId)
 * @method static float getAverageWishlistValueByCustomer(int $customerId)
 * @method static array getWishlistGrowthStatsByCustomer(int $customerId, string $period = 'monthly')
 * @method static array getWishlistAnalyticsByProduct(int $productId)
 * @method static array getWishlistAnalyticsByCategory(int $categoryId)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO|null updateWishlistItem(int $wishlistId, array $data)
 * @method static \Illuminate\Database\Eloquent\Collection getCustomerWishlistWithFilters(int $customerId, array $filters = [])
 * @method static \Illuminate\Database\Eloquent\Collection getPersonalizedWishlistRecommendations(int $customerId, int $limit = 10)
 * @method static array processWishlistPriceUpdates()
 * @method static array getWishlistDashboardData(int $customerId)
 * @method static bool shareWishlist(int $sourceCustomerId, int $targetCustomerId, array $options = [])
 * @method static array compareWishlists(int $customerId1, int $customerId2)
 * @method static array getWishlistInsights(int $customerId)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO createCustomerWishlist(array $data)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO|null updateCustomerWishlist(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist, array $data)
 * @method static bool deleteCustomerWishlist(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist)
 * @method static \Illuminate\Database\Eloquent\Collection findByCustomerId(int $customerId)
 * @method static \Illuminate\Database\Eloquent\Collection findByCustomerIdDTO(int $customerId)
 * @method static \Illuminate\Database\Eloquent\Collection findByProductId(int $productId)
 * @method static \Illuminate\Database\Eloquent\Collection findByProductIdDTO(int $productId)
 * @method static \Fereydooni\Shopping\app\Models\CustomerWishlist|null findByCustomerAndProduct(int $customerId, int $productId)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO|null findByCustomerAndProductDTO(int $customerId, int $productId)
 * @method static \Illuminate\Database\Eloquent\Collection findPublic()
 * @method static \Illuminate\Database\Eloquent\Collection findPublicDTO()
 * @method static \Illuminate\Database\Eloquent\Collection findPrivate()
 * @method static \Illuminate\Database\Eloquent\Collection findPrivateDTO()
 * @method static \Illuminate\Database\Eloquent\Collection findByPriority(string $priority)
 * @method static \Illuminate\Database\Eloquent\Collection findByPriorityDTO(string $priority)
 * @method static \Illuminate\Database\Eloquent\Collection findByDateRange(string $startDate, string $endDate)
 * @method static \Illuminate\Database\Eloquent\Collection findByDateRangeDTO(string $startDate, string $endDate)
 * @method static \Illuminate\Database\Eloquent\Collection findByPriceRange(float $minPrice, float $maxPrice)
 * @method static \Illuminate\Database\Eloquent\Collection findByPriceRangeDTO(float $minPrice, float $maxPrice)
 * @method static \Illuminate\Database\Eloquent\Collection findWithPriceDrops()
 * @method static \Illuminate\Database\Eloquent\Collection findWithPriceDropsDTO()
 * @method static \Illuminate\Database\Eloquent\Collection findNotified()
 * @method static \Illuminate\Database\Eloquent\Collection findNotifiedDTO()
 * @method static \Illuminate\Database\Eloquent\Collection findNotNotified()
 * @method static \Illuminate\Database\Eloquent\Collection findNotNotifiedDTO()
 * @method static \Fereydooni\Shopping\app\Models\CustomerWishlist create(array $data)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO createAndReturnDTO(array $data)
 * @method static bool update(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist, array $data)
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO|null updateAndReturnDTO(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist, array $data)
 * @method static bool delete(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist)
 * @method static bool addToWishlist(int $customerId, int $productId, array $data = [])
 * @method static \Fereydooni\Shopping\app\DTOs\CustomerWishlistDTO|null addToWishlistDTO(int $customerId, int $productId, array $data = [])
 * @method static bool removeFromWishlist(int $customerId, int $productId)
 * @method static bool makePublic(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist)
 * @method static bool makePrivate(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist)
 * @method static bool setPriority(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist, string $priority)
 * @method static bool markAsNotified(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist)
 * @method static bool markAsNotNotified(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist)
 * @method static bool updateCurrentPrice(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist, float $currentPrice)
 * @method static bool checkPriceDrop(\Fereydooni\Shopping\app\Models\CustomerWishlist $wishlist)
 * @method static int getWishlistCount()
 * @method static int getWishlistCountByProduct(int $productId)
 * @method static int getPublicWishlistCount()
 * @method static int getPrivateWishlistCount()
 * @method static int getWishlistCountByPriority(string $priority)
 * @method static float getTotalWishlistValue()
 * @method static float getAverageWishlistValue()
 * @method static \Illuminate\Database\Eloquent\Collection search(string $query)
 * @method static \Illuminate\Database\Eloquent\Collection searchDTO(string $query)
 * @method static \Illuminate\Database\Eloquent\Collection searchByCustomer(int $customerId, string $query)
 * @method static \Illuminate\Database\Eloquent\Collection searchByCustomerDTO(int $customerId, string $query)
 * @method static \Illuminate\Database\Eloquent\Collection getWishlistByPriority(int $customerId)
 * @method static \Illuminate\Database\Eloquent\Collection getWishlistByPriorityDTO(int $customerId)
 * @method static \Illuminate\Database\Eloquent\Collection getWishlistByDateAdded(int $customerId, string $order = 'desc')
 * @method static \Illuminate\Database\Eloquent\Collection getWishlistByDateAddedDTO(int $customerId, string $order = 'desc')
 * @method static \Illuminate\Database\Eloquent\Collection getWishlistByPrice(int $customerId, string $order = 'desc')
 * @method static \Illuminate\Database\Eloquent\Collection getWishlistByPriceDTO(int $customerId, string $order = 'desc')
 * @method static array getWishlistStatsByProduct(int $productId)
 * @method static array getWishlistStatsByCategory(int $categoryId)
 * @method static array getWishlistGrowthStats(string $period = 'monthly')
 * @method static bool validateWishlist(array $data)
 * @method static \Illuminate\Database\Eloquent\Collection getWishlistRecommendationsDTO(int $customerId, int $limit = 10)
 * @method static \Illuminate\Database\Eloquent\Collection getSimilarWishlistsDTO(int $customerId, int $limit = 10)
 * @method static array exportWishlist(int $customerId)
 * @method static bool importWishlist(int $customerId, array $wishlistItems)
 * @method static bool clearWishlist(int $customerId)
 * @method static bool moveWishlistItem(int $wishlistId, int $newPosition)
 * @method static bool duplicateWishlist(int $sourceCustomerId, int $targetCustomerId)
 */
class CustomerWishlist extends Facade
{
    /**
     * Get the registered name of the component.
     */
    protected static function getFacadeAccessor(): string
    {
        return CustomerWishlistService::class;
    }
}
