<?php

namespace Fereydooni\Shopping\app\Facades;

use Illuminate\Support\Facades\Facade;

/**
 * @method static \Illuminate\Database\Eloquent\Collection all()
 * @method static \Illuminate\Database\Eloquent\Collection allDTO()
 * @method static \Illuminate\Pagination\LengthAwarePaginator paginate(int $perPage = 15)
 * @method static \Illuminate\Pagination\Paginator simplePaginate(int $perPage = 15)
 * @method static \Illuminate\Pagination\CursorPaginator cursorPaginate(int $perPage = 15, string $cursor = null)
 * @method static \Fereydooni\Shopping\app\Models\Shipment|null find(int $id)
 * @method static \Fereydooni\Shopping\app\DTOs\ShipmentDTO|null findDTO(int $id)
 * @method static \Illuminate\Database\Eloquent\Collection findByOrderId(int $orderId)
 * @method static \Illuminate\Database\Eloquent\Collection findByOrderIdDTO(int $orderId)
 * @method static \Illuminate\Database\Eloquent\Collection findByCarrier(string $carrier)
 * @method static \Illuminate\Database\Eloquent\Collection findByCarrierDTO(string $carrier)
 * @method static \Illuminate\Database\Eloquent\Collection findByStatus(string $status)
 * @method static \Illuminate\Database\Eloquent\Collection findByStatusDTO(string $status)
 * @method static \Fereydooni\Shopping\app\Models\Shipment|null findByTrackingNumber(string $trackingNumber)
 * @method static \Fereydooni\Shopping\app\DTOs\ShipmentDTO|null findByTrackingNumberDTO(string $trackingNumber)
 * @method static \Fereydooni\Shopping\app\Models\Shipment create(array $data)
 * @method static \Fereydooni\Shopping\app\DTOs\ShipmentDTO createDTO(array $data)
 * @method static bool update(\Fereydooni\Shopping\app\Models\Shipment $shipment, array $data)
 * @method static \Fereydooni\Shopping\app\DTOs\ShipmentDTO|null updateDTO(\Fereydooni\Shopping\app\Models\Shipment $shipment, array $data)
 * @method static bool delete(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool ship(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool deliver(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool return(\Fereydooni\Shopping\app\Models\Shipment $shipment, string $reason = null)
 * @method static bool updateTracking(\Fereydooni\Shopping\app\Models\Shipment $shipment, string $trackingNumber)
 * @method static bool updateStatus(\Fereydooni\Shopping\app\Models\Shipment $shipment, string $status)
 * @method static bool updateDeliveryDate(\Fereydooni\Shopping\app\Models\Shipment $shipment, string $deliveryDate)
 * @method static \Illuminate\Database\Eloquent\Collection getPending()
 * @method static \Illuminate\Database\Eloquent\Collection getPendingDTO()
 * @method static \Illuminate\Database\Eloquent\Collection getInTransit()
 * @method static \Illuminate\Database\Eloquent\Collection getInTransitDTO()
 * @method static \Illuminate\Database\Eloquent\Collection getDelivered()
 * @method static \Illuminate\Database\Eloquent\Collection getDeliveredDTO()
 * @method static \Illuminate\Database\Eloquent\Collection getReturned()
 * @method static \Illuminate\Database\Eloquent\Collection getReturnedDTO()
 * @method static \Illuminate\Database\Eloquent\Collection getOverdue()
 * @method static \Illuminate\Database\Eloquent\Collection getOverdueDTO()
 * @method static \Illuminate\Database\Eloquent\Collection getDelayed()
 * @method static \Illuminate\Database\Eloquent\Collection getDelayedDTO()
 * @method static \Illuminate\Database\Eloquent\Collection getOnTime()
 * @method static \Illuminate\Database\Eloquent\Collection getOnTimeDTO()
 * @method static \Illuminate\Database\Eloquent\Collection search(string $query)
 * @method static \Illuminate\Database\Eloquent\Collection searchDTO(string $query)
 * @method static \Illuminate\Database\Eloquent\Collection searchByOrderId(int $orderId, string $query)
 * @method static \Illuminate\Database\Eloquent\Collection searchByOrderIdDTO(int $orderId, string $query)
 * @method static \Illuminate\Database\Eloquent\Collection searchByCarrier(string $carrier, string $query)
 * @method static \Illuminate\Database\Eloquent\Collection searchByCarrierDTO(string $carrier, string $query)
 * @method static int getCount()
 * @method static int getCountByOrderId(int $orderId)
 * @method static int getCountByCarrier(string $carrier)
 * @method static int getCountByStatus(string $status)
 * @method static \Illuminate\Database\Eloquent\Collection getCarriers()
 * @method static \Illuminate\Database\Eloquent\Collection getTrackingNumbers()
 * @method static array getAnalytics(int $shipmentId)
 * @method static array getAnalyticsByOrder(int $orderId)
 * @method static array getAnalyticsByCarrier(string $carrier)
 * @method static array getDeliveryPerformance(string $carrier = null)
 * @method static array getShippingCosts(string $carrier = null)
 * @method static array getDeliveryTimes(string $carrier = null)
 * @method static array getReturnRates(string $carrier = null)
 * @method static array getCarrierPerformance()
 * @method static array getTrends(string $period = 'month')
 * @method static array getForecast(string $period = 'month')
 * @method static array getTrackingInfo(string $trackingNumber, string $carrier)
 * @method static string createShippingLabel(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool voidShippingLabel(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static string getShippingLabel(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static string getReturnLabel(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool schedulePickup(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool cancelPickup(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static array getPickupConfirmation(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool validateTrackingNumber(string $trackingNumber, string $carrier)
 * @method static float calculateShippingCost(array $packageData)
 * @method static string estimateDeliveryDate(string $carrier, string $origin, string $destination)
 * @method static array getCarrierRates(string $carrier, array $packageData)
 * @method static array getSummary()
 * @method static array getDashboardData()
 * @method static bool changeStatus(\Fereydooni\Shopping\app\Models\Shipment $shipment, string $newStatus, string $reason = null)
 * @method static bool cancel(\Fereydooni\Shopping\app\Models\Shipment $shipment, string $reason = null)
 * @method static bool markAsPaid(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool markAsShipped(\Fereydooni\Shopping\app\Models\Shipment $shipment, string $trackingNumber = null)
 * @method static bool markAsCompleted(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static \Illuminate\Database\Eloquent\Collection getByStatus(string $status)
 * @method static \Illuminate\Database\Eloquent\Collection getByStatusDTO(string $status)
 * @method static \Illuminate\Database\Eloquent\Collection getPendingOrders()
 * @method static bool updateTracking(\Fereydooni\Shopping\app\Models\Shipment $shipment, string $trackingNumber)
 * @method static array getTrackingInfo(string $trackingNumber, string $carrier)
 * @method static bool validateTrackingNumber(string $trackingNumber, string $carrier)
 * @method static \Fereydooni\Shopping\app\Models\Shipment|null findByTrackingNumber(string $trackingNumber)
 * @method static \Illuminate\Database\Eloquent\Collection getTrackingNumbers()
 * @method static \Illuminate\Database\Eloquent\Collection searchByTracking(string $query)
 * @method static array getTrackingAnalytics(int $itemId)
 * @method static array getTrackingPerformance(string $carrier = null)
 * @method static array getTrackingHistory(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool isTrackingAvailable(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static string getTrackingStatus(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static string|null getEstimatedDeliveryFromTracking(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static string|null getCurrentLocationFromTracking(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static array getTrackingEvents(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool isTrackingOverdue(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static array getTrackingAlerts(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool updateDeliveryDate(\Fereydooni\Shopping\app\Models\Shipment $shipment, string $deliveryDate)
 * @method static bool confirmDelivery(\Fereydooni\Shopping\app\Models\Shipment $shipment, string $deliveryDate = null)
 * @method static \Illuminate\Database\Eloquent\Collection getOverdueDeliveries()
 * @method static \Illuminate\Database\Eloquent\Collection getDelayedDeliveries()
 * @method static \Illuminate\Database\Eloquent\Collection getOnTimeDeliveries()
 * @method static int|null calculateDeliveryTime(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static int|null calculateEstimatedDeliveryTime(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool isDeliveryOverdue(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool isDeliveryDelayed(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool isDeliveryOnTime(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static array getDeliveryOptimizationSuggestions(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static array getDeliveryAnalytics(int $itemId)
 * @method static array getDeliveryTrends(string $period = 'month')
 * @method static array getDeliveryAlerts(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static array getDeliveryStatusSummary()
 * @method static \Illuminate\Database\Eloquent\Collection getDeliveredToday()
 * @method static array getAvailableCarriers()
 * @method static string createShippingLabel(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool voidShippingLabel(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static string getShippingLabel(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static string getReturnLabel(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static bool schedulePickup(\Fereydooni\Shopping\app\Models\Shipment $shipment, array $pickupData = [])
 * @method static bool cancelPickup(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static array getPickupConfirmation(\Fereydooni\Shopping\app\Models\Shipment $shipment)
 * @method static \Illuminate\Database\Eloquent\Collection getShipmentsByCarrier(string $carrier)
 * @method static int getShipmentCountByCarrier(string $carrier)
 * @method static bool validateCarrier(string $carrier)
 * @method static string getCarrierLabel(string $carrier)
 * @method static array getCarrierApiStatus(string $carrier)
 * @method static bool testCarrierConnection(string $carrier)
 * @method static array getCarrierCapabilities(string $carrier)
 * @method static bool carrierSupportsService(string $carrier, string $service)
 * @method static array getCarrierServiceOptions(string $carrier)
 * @method static array getCarrierAnalytics(string $carrier = null)
 * @method static array getCarrierRecommendations(array $packageData)
 * @method static array getShipmentAnalytics(int $shipmentId)
 * @method static array getShipmentAnalyticsByOrder(int $orderId)
 * @method static array getShipmentAnalyticsByCarrier(string $carrier)
 * @method static array getShipmentCount()
 * @method static array getShipmentCountByStatus(string $status)
 * @method static array getShipmentCountByCarrier(string $carrier)
 * @method static array getShipmentCountByOrderId(int $orderId)
 * @method static array getAnalyticsSummary()
 * @method static array getPerformanceMetrics()
 */
class Shipment extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'shopping.shipment';
    }
}
