<?php

namespace Fereydooni\Shopping\database\seeders;

use Fereydooni\Shopping\app\Enums\BrandStatus;
use Illuminate\Database\Seeder;
use Fereydooni\Shopping\app\Models\Brand;

class BrandSeeder extends Seeder
{
    public function run(): void
    {
        $brands = [
            [
                'name' => 'Apple',
                'slug' => 'apple',
                'description' => 'American multinational technology company that specializes in consumer electronics, computer software, and online services.',
                'status' => BrandStatus::INACTIVE,
                'website' => 'https://www.apple.com',
                'email' => 'contact@apple.com',
                'phone' => '+1-800-275-2273',
                'founded_year' => 1976,
                'headquarters' => 'Cupertino, California, USA',
                'meta_title' => 'Apple - Innovation at its finest',
                'meta_description' => 'Discover the innovative world of Apple products including iPhone, iPad, Mac, and more.',
                'meta_keywords' => 'apple, iphone, ipad, mac, innovation, technology',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Samsung',
                'slug' => 'samsung',
                'description' => 'South Korean multinational conglomerate headquartered in Samsung Town, Seoul.',
                'status' => BrandStatus::ACTIVE,
                'website' => 'https://www.samsung.com',
                'email' => 'info@samsung.com',
                'phone' => '+82-2-2255-0114',
                'founded_year' => 1938,
                'headquarters' => 'Seoul, South Korea',
                'meta_title' => 'Samsung - Inspire the world, create the future',
                'meta_description' => 'Explore Samsung\'s innovative smartphones, tablets, TVs, and home appliances.',
                'meta_keywords' => 'samsung, galaxy, smartphone, electronics, innovation',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Nike',
                'slug' => 'nike',
                'description' => 'American multinational corporation that is engaged in the design, development, manufacturing, and worldwide marketing and sales of footwear, apparel, equipment, accessories, and services.',
                'status' => BrandStatus::PENDING,
                'website' => 'https://www.nike.com',
                'email' => 'info@nike.com',
                'phone' => '+1-503-671-6453',
                'founded_year' => 1964,
                'headquarters' => 'Beaverton, Oregon, USA',
                'meta_title' => 'Nike - Just Do It',
                'meta_description' => 'Find the latest Nike shoes, clothing, and gear for sports and lifestyle.',
                'meta_keywords' => 'nike, shoes, sportswear, athletics, just do it',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Adidas',
                'slug' => 'adidas',
                'description' => 'German multinational corporation, founded and headquartered in Herzogenaurach, Germany, that designs and manufactures shoes, clothing and accessories.',
                'status' => BrandStatus::SUSPENDED,
                'website' => 'https://www.adidas.com',
                'email' => 'contact@adidas.com',
                'phone' => '+49-9132-84-0',
                'founded_year' => 1949,
                'headquarters' => 'Herzogenaurach, Germany',
                'meta_title' => 'Adidas - Impossible is Nothing',
                'meta_description' => 'Shop Adidas for the latest in athletic shoes, clothing, and gear.',
                'meta_keywords' => 'adidas, shoes, sportswear, athletics, three stripes',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'IKEA',
                'slug' => 'ikea',
                'description' => 'Swedish-founded multinational conglomerate that designs and sells ready-to-assemble furniture, kitchen appliances and home accessories.',
                'status' => BrandStatus::ACTIVE,
                'website' => 'https://www.ikea.com',
                'email' => 'contact@ikea.com',
                'phone' => '+46-476-81000',
                'founded_year' => 1943,
                'headquarters' => 'Delft, Netherlands',
                'meta_title' => 'IKEA - Affordable furniture and home furnishing',
                'meta_description' => 'Shop IKEA for affordable furniture, home decor, and kitchen essentials.',
                'meta_keywords' => 'ikea, furniture, home decor, affordable, scandinavian design',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'name' => 'Sony',
                'slug' => 'sony',
                'description' => 'Japanese multinational conglomerate corporation headquartered in Kōnan, Minato, Tokyo.',
                'status' => BrandStatus::ACTIVE,
                'website' => 'https://www.sony.com',
                'email' => 'info@sony.com',
                'phone' => '+81-3-6748-2111',
                'founded_year' => 1946,
                'headquarters' => 'Tokyo, Japan',
                'meta_title' => 'Sony - Be Moved',
                'meta_description' => 'Discover Sony\'s range of electronics, gaming, and entertainment products.',
                'meta_keywords' => 'sony, electronics, playstation, cameras, entertainment',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 6,
            ],
            [
                'name' => 'LG',
                'slug' => 'lg',
                'description' => 'South Korean multinational electronics company headquartered in Yeouido-dong, Seoul, South Korea.',
                'status' => BrandStatus::ACTIVE,
                'website' => 'https://www.lg.com',
                'email' => 'contact@lg.com',
                'phone' => '+82-2-3777-1114',
                'founded_year' => 1958,
                'headquarters' => 'Seoul, South Korea',
                'meta_title' => 'LG - Life\'s Good',
                'meta_description' => 'Explore LG\'s innovative home appliances, TVs, and mobile devices.',
                'meta_keywords' => 'lg, electronics, home appliances, tv, mobile',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'Dell',
                'slug' => 'dell',
                'description' => 'American multinational computer technology company that develops, sells, repairs, and supports computers and related products and services.',
                'status' => BrandStatus::ACTIVE,
                'website' => 'https://www.dell.com',
                'email' => 'info@dell.com',
                'phone' => '+1-800-915-3355',
                'founded_year' => 1984,
                'headquarters' => 'Round Rock, Texas, USA',
                'meta_title' => 'Dell - Technology that drives human progress',
                'meta_description' => 'Shop Dell for laptops, desktops, servers, and enterprise solutions.',
                'meta_keywords' => 'dell, computers, laptops, desktops, enterprise',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'name' => 'HP',
                'slug' => 'hp',
                'description' => 'American multinational information technology company headquartered in Palo Alto, California.',
                'status' => BrandStatus::ACTIVE,
                'website' => 'https://www.hp.com',
                'email' => 'contact@hp.com',
                'phone' => '+1-650-857-1501',
                'founded_year' => 1939,
                'headquarters' => 'Palo Alto, California, USA',
                'meta_title' => 'HP - Keep Reinventing',
                'meta_description' => 'Discover HP\'s range of computers, printers, and technology solutions.',
                'meta_keywords' => 'hp, computers, printers, technology, business solutions',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 9,
            ],
            [
                'name' => 'Microsoft',
                'slug' => 'microsoft',
                'description' => 'American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.',
                'status' => BrandStatus::ACTIVE,
                'website' => 'https://www.microsoft.com',
                'email' => 'info@microsoft.com',
                'phone' => '+1-425-882-8080',
                'founded_year' => 1975,
                'headquarters' => 'Redmond, Washington, USA',
                'meta_title' => 'Microsoft - Empower every person and organization',
                'meta_description' => 'Explore Microsoft\'s productivity software, cloud services, and devices.',
                'meta_keywords' => 'microsoft, windows, office, azure, surface, xbox',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 10,
            ],
        ];

        foreach ($brands as $brand) {
            Brand::create($brand);
        }
    }
}
