<?php

namespace Fereydooni\Shopping\database\seeders;

use Fereydooni\Shopping\app\Enums\EmployeeStatus;
use Fereydooni\Shopping\app\Enums\EmploymentType;
use Fereydooni\Shopping\app\Enums\Gender;
use Fereydooni\Shopping\app\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $departments = [
            'Engineering',
            'Marketing',
            'Sales',
            'Human Resources',
            'Finance',
            'Operations',
            'Customer Support',
            'Product Management',
            'Design',
            'Legal',
        ];

        $positions = [
            'Software Engineer',
            'Senior Software Engineer',
            'Lead Engineer',
            'Engineering Manager',
            'Marketing Specialist',
            'Marketing Manager',
            'Sales Representative',
            'Sales Manager',
            'HR Specialist',
            'HR Manager',
            'Financial Analyst',
            'Finance Manager',
            'Operations Specialist',
            'Operations Manager',
            'Customer Support Representative',
            'Customer Support Manager',
            'Product Manager',
            'Senior Product Manager',
            'UI/UX Designer',
            'Legal Counsel',
        ];

        $employees = [
            [
                'user_id' => 1,
                'employee_number' => 'EMP001',
                'first_name' => 'John',
                'last_name' => 'Doe',
                'email' => 'john.doe@company.com',
                'phone' => '+1234567890',
                'date_of_birth' => '1990-05-15',
                'gender' => Gender::MALE,
                'hire_date' => '2020-01-15',
                'position' => 'Senior Software Engineer',
                'department' => 'Engineering',
                'manager_id' => null,
                'salary' => 85000.00,
                'hourly_rate' => 40.87,
                'employment_type' => EmploymentType::FULL_TIME,
                'status' => EmployeeStatus::ACTIVE,
                'emergency_contact_name' => 'Jane Doe',
                'emergency_contact_phone' => '+1234567891',
                'emergency_contact_relationship' => 'Spouse',
                'address' => '123 Main St',
                'city' => 'New York',
                'state' => 'NY',
                'postal_code' => '10001',
                'country' => 'USA',
                'tax_id' => '123-45-6789',
                'social_security_number' => '123-45-6789',
                'bank_account_number' => '1234567890',
                'bank_routing_number' => '021000021',
                'benefits_enrolled' => true,
                'vacation_days_used' => 5,
                'vacation_days_total' => 20,
                'sick_days_used' => 2,
                'sick_days_total' => 10,
                'performance_rating' => 4.5,
                'last_review_date' => '2023-12-01',
                'next_review_date' => '2024-06-01',
                'training_completed' => ['Laravel', 'Vue.js', 'Docker'],
                'certifications' => ['AWS Certified Developer', 'Laravel Certified Developer'],
                'skills' => ['PHP', 'Laravel', 'Vue.js', 'MySQL', 'Docker'],
                'notes' => 'Excellent team player with strong technical skills.',
            ],
            [
                'user_id' => 2,
                'employee_number' => 'EMP002',
                'first_name' => 'Jane',
                'last_name' => 'Smith',
                'email' => 'jane.smith@company.com',
                'phone' => '+1234567892',
                'date_of_birth' => '1988-08-22',
                'gender' => Gender::FEMALE,
                'hire_date' => '2019-03-10',
                'position' => 'Marketing Manager',
                'department' => 'Marketing',
                'manager_id' => null,
                'salary' => 75000.00,
                'hourly_rate' => 36.06,
                'employment_type' => EmploymentType::FULL_TIME,
                'status' => EmployeeStatus::ACTIVE,
                'emergency_contact_name' => 'Bob Smith',
                'emergency_contact_phone' => '+1234567893',
                'emergency_contact_relationship' => 'Spouse',
                'address' => '456 Oak Ave',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'postal_code' => '90210',
                'country' => 'USA',
                'tax_id' => '987-65-4321',
                'social_security_number' => '987-65-4321',
                'bank_account_number' => '0987654321',
                'bank_routing_number' => '121000248',
                'benefits_enrolled' => true,
                'vacation_days_used' => 8,
                'vacation_days_total' => 20,
                'sick_days_used' => 1,
                'sick_days_total' => 10,
                'performance_rating' => 4.8,
                'last_review_date' => '2023-11-15',
                'next_review_date' => '2024-05-15',
                'training_completed' => ['Digital Marketing', 'Google Analytics', 'Social Media Management'],
                'certifications' => ['Google Analytics Individual Qualification', 'HubSpot Marketing Certification'],
                'skills' => ['Digital Marketing', 'Social Media', 'Google Analytics', 'Content Creation'],
                'notes' => 'Creative and results-driven marketing professional.',
            ],
            [
                'user_id' => 3,
                'employee_number' => 'EMP003',
                'first_name' => 'Mike',
                'last_name' => 'Johnson',
                'email' => 'mike.johnson@company.com',
                'phone' => '+1234567894',
                'date_of_birth' => '1992-12-03',
                'gender' => Gender::MALE,
                'hire_date' => '2021-06-20',
                'position' => 'Sales Representative',
                'department' => 'Sales',
                'manager_id' => null,
                'salary' => 60000.00,
                'hourly_rate' => 28.85,
                'employment_type' => EmploymentType::FULL_TIME,
                'status' => EmployeeStatus::ACTIVE,
                'emergency_contact_name' => 'Sarah Johnson',
                'emergency_contact_phone' => '+1234567895',
                'emergency_contact_relationship' => 'Spouse',
                'address' => '789 Pine St',
                'city' => 'Chicago',
                'state' => 'IL',
                'postal_code' => '60601',
                'country' => 'USA',
                'tax_id' => '456-78-9012',
                'social_security_number' => '456-78-9012',
                'bank_account_number' => '4567890123',
                'bank_routing_number' => '071000013',
                'benefits_enrolled' => true,
                'vacation_days_used' => 3,
                'vacation_days_total' => 20,
                'sick_days_used' => 0,
                'sick_days_total' => 10,
                'performance_rating' => 4.2,
                'last_review_date' => '2023-10-01',
                'next_review_date' => '2024-04-01',
                'training_completed' => ['Sales Techniques', 'CRM Software', 'Negotiation Skills'],
                'certifications' => ['Salesforce Certified Sales Representative'],
                'skills' => ['Sales', 'CRM', 'Negotiation', 'Customer Relationship Management'],
                'notes' => 'Motivated sales professional with strong closing skills.',
            ],
            [
                'user_id' => 4,
                'employee_number' => 'EMP004',
                'first_name' => 'Sarah',
                'last_name' => 'Wilson',
                'email' => 'sarah.wilson@company.com',
                'phone' => '+1234567896',
                'date_of_birth' => '1985-04-18',
                'gender' => Gender::FEMALE,
                'hire_date' => '2018-09-05',
                'position' => 'HR Manager',
                'department' => 'Human Resources',
                'manager_id' => null,
                'salary' => 70000.00,
                'hourly_rate' => 33.65,
                'employment_type' => EmploymentType::FULL_TIME,
                'status' => EmployeeStatus::ACTIVE,
                'emergency_contact_name' => 'Tom Wilson',
                'emergency_contact_phone' => '+1234567897',
                'emergency_contact_relationship' => 'Spouse',
                'address' => '321 Elm St',
                'city' => 'Houston',
                'state' => 'TX',
                'postal_code' => '77001',
                'country' => 'USA',
                'tax_id' => '789-01-2345',
                'social_security_number' => '789-01-2345',
                'bank_account_number' => '7890123456',
                'bank_routing_number' => '113000023',
                'benefits_enrolled' => true,
                'vacation_days_used' => 12,
                'vacation_days_total' => 20,
                'sick_days_used' => 3,
                'sick_days_total' => 10,
                'performance_rating' => 4.6,
                'last_review_date' => '2023-09-15',
                'next_review_date' => '2024-03-15',
                'training_completed' => ['HR Management', 'Employment Law', 'Benefits Administration'],
                'certifications' => ['PHR Certification', 'SHRM-CP'],
                'skills' => ['HR Management', 'Employee Relations', 'Benefits Administration', 'Recruitment'],
                'notes' => 'Experienced HR professional with strong interpersonal skills.',
            ],
            [
                'user_id' => 5,
                'employee_number' => 'EMP005',
                'first_name' => 'David',
                'last_name' => 'Brown',
                'email' => 'david.brown@company.com',
                'phone' => '+1234567898',
                'date_of_birth' => '1991-07-30',
                'gender' => Gender::MALE,
                'hire_date' => '2022-01-10',
                'position' => 'Financial Analyst',
                'department' => 'Finance',
                'manager_id' => null,
                'salary' => 65000.00,
                'hourly_rate' => 31.25,
                'employment_type' => EmploymentType::FULL_TIME,
                'status' => EmployeeStatus::ACTIVE,
                'emergency_contact_name' => 'Lisa Brown',
                'emergency_contact_phone' => '+1234567899',
                'emergency_contact_relationship' => 'Spouse',
                'address' => '654 Maple Dr',
                'city' => 'Phoenix',
                'state' => 'AZ',
                'postal_code' => '85001',
                'country' => 'USA',
                'tax_id' => '234-56-7890',
                'social_security_number' => '234-56-7890',
                'bank_account_number' => '2345678901',
                'bank_routing_number' => '122101706',
                'benefits_enrolled' => true,
                'vacation_days_used' => 7,
                'vacation_days_total' => 20,
                'sick_days_used' => 1,
                'sick_days_total' => 10,
                'performance_rating' => 4.3,
                'last_review_date' => '2023-08-01',
                'next_review_date' => '2024-02-01',
                'training_completed' => ['Financial Analysis', 'Excel Advanced', 'Accounting Principles'],
                'certifications' => ['CFA Level 1', 'Excel Expert Certification'],
                'skills' => ['Financial Analysis', 'Excel', 'Accounting', 'Budgeting', 'Forecasting'],
                'notes' => 'Detail-oriented financial analyst with strong analytical skills.',
            ],
        ];

        foreach ($employees as $employeeData) {
            Employee::create($employeeData);
        }

        $this->command->info('Employee data seeded successfully!');
    }
}
